#!/bin/bash

set -e -u

ACTION=
if [[ $# -ne 0 ]]
then
    ACTION=$1
    shift
fi

case $ACTION in
    export)
        TARGET=
        if [[ $# -ne 0 ]]
        then
            TARGET=$1
        fi

        _TMP=$(mktemp -d .gpg-pair.XXXXXX)
        trap 'rm -rf "$_TMP"' EXIT

        NAME=$(gpg --with-colons --fixed-list-mode --list-keys $TARGET | grep ^sub: | awk -F : '{ print $5 }')
        if [[ -z "$NAME" ]]
        then
            echo "Error finding keys ($TARGET)"
            exit 64
        fi
        NAME=$(echo $NAME | perl -e 'print join "+", map { substr $_, -8 } split m/\s+/, <STDIN>')
        gpg --export $TARGET > $_TMP/public
        gpg --export-secret-key $TARGET > $_TMP/secret
        tar cf "$NAME.tar" -C $_TMP .
        echo "$NAME.tar"
    ;;
    import)
    ;;
    *)
        cat <<_END_
Usage: gpg-pair ...

    export
    import
    
_END_
    ;;
esac
